terminal_width = 122
terminal_height = 64
base_layout = "sidebar"
theme = "solarized-dark"

[[windows]]
widget_type = "text"
name = "main"
row = 10
col = 20
rows = 40
cols = 102
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = false
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
visible = true
streams = ["main"]
buffer_size = 10000
wordwrap = true
show_timestamps = false

[[windows]]
widget_type = "command_input"
name = "command_input"
row = 63
col = 20
rows = 1
cols = 102
show_border = true
border_style = "single"
border_sides = [
    "left",
    "right",
]
border_color = "-"
show_title = true
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 1
max_rows = 1
min_cols = 20
visible = true
prompt_icon = "#"

[[windows]]
widget_type = "tabbedtext"
name = "chat"
row = 51
col = 20
rows = 12
cols = 102
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = false
title = "Chat"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
visible = true
buffer_size = 5000
tab_bar_position = "top"
tab_separator = true

[[windows.tabs]]
name = "Thoughts"
streams = ["thoughts"]
show_timestamps = true
ignore_activity = false

[[windows.tabs]]
name = "Speech"
streams = ["speech"]
show_timestamps = true
ignore_activity = false

[[windows.tabs]]
name = "Announcements"
streams = ["announcements"]
show_timestamps = false
ignore_activity = false

[[windows.tabs]]
name = "Loot"
streams = ["loot"]
show_timestamps = false
ignore_activity = false

[[windows.tabs]]
name = "Ambients"
streams = ["ambients"]
show_timestamps = true
ignore_activity = true

[[windows]]
widget_type = "text"
name = "speech"
row = 41
col = 35
rows = 10
cols = 40
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = true
title = "Speech"
title_position = "top-left"
background_color = "-"
text_color = "#FFD700"
transparent_background = false
locked = false
visible = false
streams = ["speech"]
buffer_size = 1000
wordwrap = true
show_timestamps = false

[[windows]]
widget_type = "progress"
name = "health"
row = 55
col = 0
rows = 1
cols = 20
show_border = true
border_style = "single"
border_sides = [
    "left",
    "right",
]
border_color = "-"
show_title = false
title = "Health"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 1
max_rows = 1
min_cols = 20
max_cols = 20
visible = true
id = "health"
label = "Health"
color = "#6e0202"
numbers_only = false
current_only = false

[[windows]]
widget_type = "progress"
name = "mana"
row = 54
col = 0
rows = 1
cols = 20
show_border = true
border_style = "single"
border_sides = [
    "left",
    "right",
]
border_color = "-"
show_title = false
title = "Mana"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 1
max_rows = 1
min_cols = 20
max_cols = 20
visible = true
id = "mana"
label = "Mana"
color = "#08086d"
numbers_only = false
current_only = false

[[windows]]
widget_type = "progress"
name = "stamina"
row = 53
col = 0
rows = 1
cols = 20
show_border = true
border_style = "single"
border_sides = [
    "left",
    "right",
]
border_color = "-"
show_title = false
title = "Stamina"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 1
max_rows = 1
min_cols = 20
max_cols = 20
visible = true
id = "stamina"
label = "Stamina"
color = "#bd7b00"
numbers_only = false
current_only = false

[[windows]]
widget_type = "progress"
name = "spirit"
row = 52
col = 0
rows = 1
cols = 20
show_border = true
border_style = "single"
border_sides = [
    "left",
    "right",
]
border_color = "-"
show_title = false
title = "Spirit"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 1
max_rows = 1
min_cols = 20
max_cols = 20
visible = true
id = "spirit"
label = "Spirit"
color = "#6e727c"
numbers_only = false
current_only = false

[[windows]]
widget_type = "injury_doll"
name = "injuries"
row = 57
col = 0
rows = 7
cols = 10
show_border = true
border_style = "single"
border_sides = [
    "bottom",
    "left",
]
border_color = "-"
show_title = false
title = "Injuries"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 7
max_rows = 7
min_cols = 10
max_cols = 10
visible = true
content_align = "top-right"
injury1_color = "#aa5500"
injury2_color = "#ff8800"
injury3_color = "#ff0000"
scar1_color = "#999999"
scar2_color = "#777777"
scar3_color = "#555555"

[[windows]]
widget_type = "compass"
name = "compass"
row = 60
col = 10
rows = 4
cols = 10
show_border = true
border_style = "single"
border_sides = [
    "bottom",
    "right",
]
border_color = "-"
show_title = false
title = "Compass"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 4
max_rows = 4
min_cols = 10
max_cols = 10
visible = true
content_align = "bottom-center"
active_color = "#00FF00"
inactive_color = "#333333"

[[windows]]
widget_type = "dashboard"
name = "dashboard"
row = 56
col = 0
rows = 1
cols = 20
show_border = true
border_style = "single"
border_sides = [
    "left",
    "right",
]
border_color = "-"
show_title = false
title = "Status"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 1
max_rows = 1
min_cols = 20
max_cols = 20
visible = true
dashboard_layout = "horizontal"
dashboard_spacing = 1
dashboard_hide_inactive = true

[[windows.dashboard_indicators]]
id = "poisoned"
icon = "?"
colors = [
    "#000000",
    "#00ff00",
]

[[windows]]
widget_type = "countdown"
name = "roundtime"
row = 58
col = 10
rows = 1
cols = 10
show_border = true
border_style = "single"
border_sides = ["right"]
border_color = "-"
show_title = false
title = "RT"
title_position = "top-left"
background_color = "-"
text_color = "#FF0000"
transparent_background = false
locked = false
min_rows = 1
max_rows = 1
min_cols = 10
max_cols = 10
visible = true
id = "roundtime"
icon = ""
color = "#FF0000"

[[windows]]
widget_type = "countdown"
name = "casttime"
row = 59
col = 10
rows = 1
cols = 10
show_border = true
border_style = "single"
border_sides = ["right"]
border_color = "-"
show_title = false
title = "Cast"
title_position = "top-left"
background_color = "-"
text_color = "#00BFFF"
transparent_background = false
locked = false
min_rows = 1
max_rows = 1
min_cols = 10
max_cols = 10
visible = true
id = "casttime"
icon = ""
color = "#00BFFF"

[[windows]]
widget_type = "countdown"
name = "stuntime"
row = 57
col = 10
rows = 1
cols = 10
show_border = true
border_style = "single"
border_sides = ["right"]
border_color = "-"
show_title = false
title = "Stun"
title_position = "top-left"
background_color = "-"
text_color = "#FFFF00"
transparent_background = false
locked = false
min_rows = 1
max_rows = 1
min_cols = 10
max_cols = 10
visible = true
id = "stuntime"
icon = ""
color = "#FFFF00"

[[windows]]
widget_type = "progress"
name = "pbarStance"
row = 51
col = 0
rows = 1
cols = 20
show_border = true
border_style = "single"
border_sides = [
    "left",
    "right",
]
border_color = "-"
show_title = false
title = "Stance"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 1
max_rows = 1
min_cols = 20
max_cols = 20
visible = true
id = "pbarStance"
label = "Stance"
color = "#000080"
numbers_only = false
current_only = false

[[windows]]
widget_type = "progress"
name = "encumlevel"
row = 50
col = 0
rows = 1
cols = 20
show_border = true
border_style = "single"
border_sides = [
    "left",
    "right",
]
border_color = "-"
show_title = false
title = "Encumbrance"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 1
max_rows = 1
min_cols = 20
max_cols = 20
visible = true
id = "encumlevel"
label = "Encumbrance"
color = "#006400"
numbers_only = false
current_only = false

[[windows]]
widget_type = "progress"
name = "mindState"
row = 49
col = 0
rows = 1
cols = 20
show_border = true
border_style = "single"
border_sides = [
    "left",
    "right",
]
border_color = "-"
show_title = false
title = "Mind"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 1
max_rows = 1
min_cols = 20
max_cols = 20
visible = true
id = "mindState"
label = "Mind"
color = "#008b8b"
numbers_only = false
current_only = false

[[windows]]
widget_type = "progress"
name = "lblBPs"
row = 47
col = 0
rows = 2
cols = 20
show_border = true
border_style = "single"
border_sides = [
    "top",
    "left",
    "right",
]
border_color = "-"
show_title = true
title = "Status"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 2
max_rows = 2
min_cols = 20
max_cols = 20
visible = true
id = "lblBPs"
label = "Blood Points"
color = "#451349"
numbers_only = false
current_only = false

[[windows]]
widget_type = "room"
name = "room"
row = 0
col = 20
rows = 10
cols = 102
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = true
title = "Room"
title_position = "bottom-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 5
visible = true
buffer_size = 0
show_desc = true
show_objs = true
show_players = true
show_exits = true
show_name = false

[[windows]]
widget_type = "players"
name = "players"
row = 46
col = 0
rows = 1
cols = 20
show_border = true
border_style = "single"
border_sides = [
    "top",
    "left",
    "right",
]
border_color = "-"
show_title = true
title = "Players"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 1
max_rows = 1
min_cols = 20
max_cols = 20
visible = true
entity_id = "playercount"

[[windows]]
widget_type = "targets"
name = "targets"
row = 39
col = 0
rows = 7
cols = 20
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = true
title = "Targets"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 4
min_cols = 20
max_cols = 20
visible = true
entity_id = "targetcount"

[[windows]]
widget_type = "active_effects"
name = "debuffs"
row = 34
col = 0
rows = 5
cols = 20
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = true
title = "Debuffs"
title_position = "top-left"
background_color = "-"
text_color = "#FF0000"
transparent_background = false
locked = false
min_rows = 5
max_rows = 5
min_cols = 20
max_cols = 20
visible = true
category = "Debuffs"

[[windows]]
widget_type = "active_effects"
name = "cooldowns"
row = 29
col = 0
rows = 5
cols = 20
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = true
title = "Cooldowns"
title_position = "top-left"
background_color = "-"
text_color = "#FFA500"
transparent_background = false
locked = false
min_rows = 5
max_rows = 5
min_cols = 20
max_cols = 20
visible = true
category = "Cooldowns"

[[windows]]
widget_type = "active_effects"
name = "buffs"
row = 19
col = 0
rows = 10
cols = 20
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = true
title = "Buffs"
title_position = "top-left"
background_color = "-"
text_color = "#00FF00"
transparent_background = false
locked = false
min_rows = 10
max_rows = 10
min_cols = 20
max_cols = 20
visible = true
category = "Buffs"

[[windows]]
widget_type = "hand"
name = "left"
row = 50
col = 20
rows = 1
cols = 34
show_border = true
border_style = "single"
border_sides = ["left"]
border_color = "-"
show_title = false
title = "Left Hand"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 1
max_rows = 1
visible = true
icon = "L:"

[[windows]]
widget_type = "hand"
name = "right"
row = 50
col = 54
rows = 1
cols = 34
show_border = true
border_style = "single"
border_sides = ["left"]
border_color = "-"
show_title = false
title = "Right Hand"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 1
max_rows = 1
visible = true
icon = "R:"

[[windows]]
widget_type = "hand"
name = "spell"
row = 50
col = 88
rows = 1
cols = 34
show_border = true
border_style = "single"
border_sides = [
    "left",
    "right",
]
border_color = "-"
show_title = false
title = "Spell"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 1
max_rows = 1
visible = true
icon = "S:"

[[windows]]
widget_type = "active_effects"
name = "active_spells"
row = 9
col = 0
rows = 10
cols = 20
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = true
title = "Active Spells"
title_position = "top-left"
background_color = "-"
text_color = "#00BFFF"
transparent_background = false
locked = false
min_cols = 20
max_cols = 20
visible = true
category = "ActiveSpells"

[[windows]]
widget_type = "text"
name = "bounty"
row = 0
col = 0
rows = 9
cols = 20
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = true
title = "Bounties"
title_position = "top-left"
background_color = "-"
text_color = "#FFD700"
transparent_background = false
locked = false
min_cols = 20
max_cols = 20
visible = true
streams = ["bounty"]
buffer_size = 0
wordwrap = true
show_timestamps = false

[[windows]]
widget_type = "countdown"
name = "countdown_custom"
row = 4
col = 0
rows = 3
cols = 20
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = true
title = "Custom"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
visible = false
id = "roundtime"
icon = ""
