terminal_width = 122
terminal_height = 69
base_layout = "test3"
theme = "retro-terminal"

[[windows]]
widget_type = "command_input"
name = "command_input"
row = 65
col = 22
rows = 2
cols = 100
show_border = true
border_style = "single"
border_sides = [
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = true
title_position = "top-left"
background_color = "-"
text_color = "----"
transparent_background = false
locked = false
min_rows = 2
max_rows = 4
min_cols = 20
visible = true
prompt_icon = ">"

[[windows]]
widget_type = "tabbedtext"
name = "pirmary"
row = 13
col = 22
rows = 41
cols = 100
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = true
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
visible = true
buffer_size = 5000
tab_bar_position = "top"
tab_separator = true

[[windows.tabs]]
name = "Main"
streams = ["main"]
show_timestamps = false
ignore_activity = false

[[windows.tabs]]
name = "Familiar"
streams = ["familiar"]
show_timestamps = false
ignore_activity = false

[[windows]]
widget_type = "quickbar"
name = "quickbar"
row = 67
col = 0
rows = 2
cols = 122
show_border = true
border_style = "single"
border_sides = [
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = false
title = "Quickbar"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 2
max_rows = 2
visible = true

[[windows]]
widget_type = "minivitals"
name = "minivitals"
row = 64
col = 22
rows = 1
cols = 100
show_border = true
border_style = "single"
border_sides = [
    "left",
    "right",
]
border_color = "-"
show_title = false
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 1
max_rows = 1
min_cols = 40
visible = true
numbers_only = false
current_only = false
health_color = "#6e0202"
mana_color = "#08086d"
stamina_color = "#bd7b00"
spirit_color = "#6e727c"

[[windows]]
widget_type = "room"
name = "room"
row = 54
col = 22
rows = 10
cols = 100
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = true
title = "Room"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 5
visible = true
buffer_size = 0
show_desc = true
show_objs = true
show_players = true
show_exits = true
show_name = false

[[windows]]
widget_type = "hand"
name = "left"
row = 62
col = 0
rows = 2
cols = 22
show_border = true
border_style = "single"
border_sides = [
    "top",
    "left",
    "right",
]
border_color = "-"
show_title = false
title = "Left Hand"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 2
max_rows = 2
visible = true
icon = "L:"

[[windows]]
widget_type = "hand"
name = "right"
row = 64
col = 0
rows = 1
cols = 22
show_border = true
border_style = "single"
border_sides = [
    "left",
    "right",
]
border_color = "-"
show_title = false
title = "Right Hand"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 1
max_rows = 1
visible = true
icon = "R:"

[[windows]]
widget_type = "hand"
name = "spell"
row = 65
col = 0
rows = 2
cols = 22
show_border = true
border_style = "single"
border_sides = [
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = false
title = "Spell"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 2
max_rows = 2
visible = true
icon = "S:"

[[windows]]
widget_type = "injury_doll"
name = "injuries"
row = 54
col = 0
rows = 8
cols = 10
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
]
border_color = "-"
show_title = false
title = "Injuries"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 6
min_cols = 7
visible = true
content_align = "center"
injury1_color = "#aa5500"
injury2_color = "#ff8800"
injury3_color = "#ff0000"
scar1_color = "#999999"
scar2_color = "#777777"
scar3_color = "#555555"

[[windows]]
widget_type = "compass"
name = "compass"
row = 57
col = 12
rows = 5
cols = 10
show_border = true
border_style = "single"
border_sides = [
    "bottom",
    "right",
]
border_color = "-"
show_title = false
title = "Compass"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 2
min_cols = 6
visible = true
content_align = "bottom-center"
active_color = "#00FF00"
inactive_color = "#333333"

[[windows]]
widget_type = "dashboard"
name = "dashboard"
row = 54
col = 10
rows = 8
cols = 10
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
]
border_color = "-"
show_title = false
title = "Dashboard"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 3
min_cols = 2
visible = true
content_align = "bottom-left"
dashboard_layout = "vertical"
dashboard_spacing = 0
dashboard_hide_inactive = false

[[windows.dashboard_indicators]]
id = "BLEEDING"
icon = ""
colors = [
    "#555555",
    "#ff0000",
]

[[windows.dashboard_indicators]]
id = "DISEASED"
icon = ""
colors = [
    "#555555",
    "#8b4513",
]

[[windows.dashboard_indicators]]
id = "POISONED"
icon = ""
colors = [
    "#555555",
    "#00ff00",
]

[[windows.dashboard_indicators]]
id = "STUNNED"
icon = "󱐌"
colors = [
    "#555555",
    "#ffff00",
]

[[windows.dashboard_indicators]]
id = "WEBBED"
icon = "󰯊"
colors = [
    "#555555",
    "#cccccc",
]

[[windows]]
widget_type = "countdown"
name = "roundtime"
row = 54
col = 12
rows = 2
cols = 10
show_border = true
border_style = "single"
border_sides = [
    "top",
    "right",
]
border_color = "-"
show_title = false
title = "RT"
title_position = "top-left"
background_color = "-"
text_color = "#FF0000"
transparent_background = false
locked = false
visible = true
id = "roundtime"
icon = ""
color = "#FF0000"

[[windows]]
widget_type = "countdown"
name = "casttime"
row = 56
col = 12
rows = 1
cols = 10
show_border = true
border_style = "single"
border_sides = ["right"]
border_color = "-"
show_title = true
title = "Cast"
title_position = "top-left"
background_color = "-"
text_color = "#00BFFF"
transparent_background = false
locked = false
visible = true
id = "casttime"
icon = ""
color = "#00BFFF"

[[windows]]
widget_type = "progress"
name = "stance"
row = 52
col = 0
rows = 2
cols = 22
show_border = true
border_style = "single"
border_sides = [
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = false
title = "Stance"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 2
max_rows = 2
visible = true
id = "pbarStance"
label = "Stance"
color = "#000080"
numbers_only = false
current_only = false

[[windows]]
widget_type = "targets"
name = "targets"
row = 36
col = 0
rows = 13
cols = 22
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = true
title = "Targets"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 4
min_cols = 20
visible = true
entity_id = "targetcount"
show_body_part_count = false

[[windows]]
widget_type = "players"
name = "players"
row = 49
col = 0
rows = 1
cols = 22
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = true
title = "Players"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_cols = 20
visible = true
entity_id = "playercount"

[[windows]]
widget_type = "encum"
name = "encum"
row = 51
col = 0
rows = 1
cols = 22
show_border = true
border_style = "single"
border_sides = [
    "left",
    "right",
]
border_color = "-"
show_title = false
title = "Encumbrance"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 1
max_rows = 1
min_cols = 15
visible = true
align = "left"
show_label = false
color_light = "#00FF00"
color_moderate = "#FFFF00"
color_heavy = "#FFA500"
color_critical = "#FF0000"

[[windows]]
widget_type = "active_effects"
name = "debuffs"
row = 31
col = 0
rows = 5
cols = 22
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = true
title = "Debuffs"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
visible = true
category = "Debuffs"

[[windows]]
widget_type = "active_effects"
name = "buffs"
row = 16
col = 0
rows = 10
cols = 22
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = true
title = "Buffs"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
visible = true
category = "Buffs"

[[windows]]
widget_type = "active_effects"
name = "cooldowns"
row = 26
col = 0
rows = 5
cols = 22
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = true
title = "Cooldowns"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
visible = true
category = "Cooldowns"

[[windows]]
widget_type = "active_effects"
name = "active_spells"
row = 6
col = 0
rows = 10
cols = 22
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = true
title = "Active Spells"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
visible = true
category = "ActiveSpells"

[[windows]]
widget_type = "text"
name = "bounty"
row = 0
col = 0
rows = 6
cols = 22
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = true
title = "Bounties"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
visible = true
streams = ["bounty"]
buffer_size = 10
wordwrap = true
show_timestamps = false
compact = true

[[windows]]
widget_type = "gs4_experience"
name = "gs4_experience"
row = 50
col = 0
rows = 1
cols = 22
show_border = true
border_style = "single"
border_sides = [
    "left",
    "right",
]
border_color = "-"
show_title = false
title = "Experience"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
min_rows = 1
max_rows = 1
min_cols = 20
visible = true
align = "center"
show_level = false
show_exp_bar = false
mind_bar_color = "#00FFFF"

[[windows]]
widget_type = "tabbedtext"
name = "chat"
row = 0
col = 22
rows = 13
cols = 100
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = true
title = "Chat"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
visible = true
buffer_size = 5000
tab_bar_position = "top"
tab_separator = true

[[windows.tabs]]
name = "Thoughts"
streams = ["thoughts"]
show_timestamps = false
ignore_activity = false

[[windows.tabs]]
name = "Speech"
streams = ["speech"]
show_timestamps = false
ignore_activity = false

[[windows.tabs]]
name = "Announcements"
streams = ["announcements"]
show_timestamps = false
ignore_activity = false

[[windows.tabs]]
name = "Loot"
streams = ["loot"]
show_timestamps = false
ignore_activity = false

[[windows.tabs]]
name = "Ambients"
streams = ["ambients"]
show_timestamps = false
ignore_activity = false

[[windows.tabs]]
name = "Logons"
streams = ["logons"]
show_timestamps = true
ignore_activity = true

[[windows.tabs]]
name = "Deaths"
streams = ["death"]
show_timestamps = true
ignore_activity = true

[[windows]]
widget_type = "text"
name = "society"
row = 0
col = 0
rows = 15
cols = 50
show_border = true
border_style = "single"
border_sides = [
    "top",
    "bottom",
    "left",
    "right",
]
border_color = "-"
show_title = true
title = "Society Tasks"
title_position = "top-left"
background_color = "-"
text_color = "-"
transparent_background = false
locked = false
visible = false
streams = ["society"]
buffer_size = 10
wordwrap = true
show_timestamps = false
compact = false
