[book]
title = "VellumFE User Guide"
authors = ["Nisugi"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "coal"
preferred-dark-theme = "coal"
git-repository-url = "https://github.com/Nisugi/VellumFE"
